In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Load dataset
df = pd.read_csv('Housing_Price_Dataset.csv')

df.head()

,property_size,number_of_bedrooms,number_of_bathrooms,location_type,age_of_property,proximity_to_public_transport,crime_rate_in_area,school_quality_score,house_sale_price
0,3008.37,-0.346,-0.2740,Suburban,0.0474,19.890,0.03920,8.71,449268.00
1,3270.77,0.307,0.5650,Rural,0.2450,2.600,0.00271,9.36,553784.29
2,1810.05,-0.144,-0.0214,Suburban,0.1790,5.360,0.08630,6.24,277421.86
3,5171.61,1.410,0.6860,Urban,0.2560,0.401,0.01100,9.35,459590.56
4,3195.10,0.541,0.8490,Suburban,0.3550,2.730,0.02340,6.54,333659.33

In [ ]:
# Number of rows and columns
df.shape

(1000, 9)

In [ ]:
# Column Names 
df.columns.to_list()

['property_size',
 'number_of_bedrooms',
 'number_of_bathrooms',
 'location_type',
 'age_of_property',
 'proximity_to_public_transport',
 'crime_rate_in_area',
 'school_quality_score',
 'house_sale_price']

In [ ]:
# Dataset Infomation
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   property_size                  1000 non-null   float64
 1   number_of_bedrooms             1000 non-null   float64
 2   number_of_bathrooms            1000 non-null   float64
 3   location_type                  1000 non-null   str
 4   age_of_property                1000 non-null   float64
 5   proximity_to_public_transport  1000 non-null   float64
 6   crime_rate_in_area             1000 non-null   float64
 7   school_quality_score           1000 non-null   float64
 8   house_sale_price               1000 non-null   float64
dtypes: float64(8), str(1)
memory usage: 70.4 KB

In [ ]:
# Descriptive Statistic
df.describe().T

,count,mean,std,min,25%,50%,75%,max
property_size,1000.0,2647.638830,1294.745544,779.700000,1754.30750,2417.490000,3134.80250,11345.780
number_of_bedrooms,1000.0,0.046277,1.007127,-2.630000,-0.65425,0.061900,0.70225,3.850
number_of_bathrooms,1000.0,0.011666,0.985091,-2.810000,-0.63025,0.000135,0.66100,3.090
age_of_property,1000.0,0.352023,0.188704,0.028600,0.21300,0.314000,0.45500,1.210
proximity_to_public_transport,1000.0,9.901814,9.162502,0.136000,2.99750,7.120000,14.16500,62.320
crime_rate_in_area,1000.0,0.074814,0.088008,0.000005,0.01440,0.046600,0.10300,0.719
school_quality_score,1000.0,7.069930,1.633160,1.830000,5.91750,7.285000,8.37000,9.910
house_sale_price,1000.0,350137.916310,130904.595271,120520.430000,262227.04250,323881.575000,405511.94000,1202878.270

In [18]:
# Summary statistics for all columns, including categorical ones
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
property_size,1000.0,NaN,NaN,NaN,2647.63883,1294.745544,779.7,1754.3075,2417.49,3134.8025,11345.78
number_of_bedrooms,1000.0,NaN,NaN,NaN,0.046277,1.007127,-2.63,-0.65425,0.0619,0.70225,3.85
number_of_bathrooms,1000.0,NaN,NaN,NaN,0.011666,0.985091,-2.81,-0.63025,0.000135,0.661,3.09
location_type,1000,3,Suburban,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age_of_property,1000.0,NaN,NaN,NaN,0.352023,0.188704,0.0286,0.213,0.314,0.455,1.21
proximity_to_public_transport,1000.0,NaN,NaN,NaN,9.901814,9.162502,0.136,2.9975,7.12,14.165,62.32
crime_rate_in_area,1000.0,NaN,NaN,NaN,0.074814,0.088008,0.000005,0.0144,0.0466,0.103,0.719
school_quality_score,1000.0,NaN,NaN,NaN,7.06993,1.63316,1.83,5.9175,7.285,8.37,9.91
house_sale_price,1000.0,NaN,NaN,NaN,350137.91631,130904.595271,120520.43,262227.0425,323881.575,405511.94,1202878.27

In [ ]:
# Check Missing Values 
df.isnull().sum()

property_size                    0
number_of_bedrooms               0
number_of_bathrooms              0
location_type                    0
age_of_property                  0
proximity_to_public_transport    0
crime_rate_in_area               0
school_quality_score             0
house_sale_price                 0
dtype: int64

In [10]:
# Identifying Duplicates    
df.duplicated().sum()

np.int64(0)

In [26]:
# Identify Numerical and Categorical features 

# Identify Numerical columns
numerical_features = df.select_dtypes(
    include=["int64","float64"]
).columns.tolist()

# Identify categorical columns
categorical_features = df.select_dtypes(
    include=["object","category","bool"]
).columns.tolist()

print(numerical_features)
print(categorical_features)

['property_size', 'number_of_bedrooms', 'number_of_bathrooms', 'age_of_property', 'proximity_to_public_transport', 'crime_rate_in_area', 'school_quality_score', 'house_sale_price']
['location_type']

/var/folders/gm/szf58jn56nj97wr_my7w1tjc0000gn/T/ipykernel_49491/1029785553.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = df.select_dtypes(